name: Run unit tests and upload coverage results

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Run unit tests and upload coverage report to Codecov
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Set up node environment
        uses: actions/setup-node@v1

      - name: Install packages
        run: yarn install

      - name: Run unit tests
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
